package cs455.overlay.wireformats;

public interface Protocol {
    int OVERLAY_NODE_SENDS_REGISTRATION = 2;
    int REGISTRY_REPORTS_REGISTRATION_STATUS = 3;

    int OVERLAY_NODE_SENDS_DEREGISTRATION = 4;
    int REGISTRY_REPORTS_DEREGISTRATION_STATUS = 5;

    int REGISTRY_SENDS_NODE_MANIFEST = 6;
    int NODE_REPORTS_OVERLAY_SETUP_STATUS = 7;

    int REGISTRY_REQUESTS_TASK_INITIATE = 8;
    int OVERLAY_NODE_SENDS_DATA = 9;
    int OVERLAY_NODE_REPORTS_TASK_FINISHED = 10;

    int REGISTRY_REQUESTS_TRAFFIC_SUMMARY = 11;
    int OVERLAY_NODE_REPORTS_TRAFFIC_SUMMARY = 12;
}
